# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='password',
        ),
    ]
